<?php

namespace Database\Seeders;

use App\Models\Setting;
use Illuminate\Database\Seeder;

class ConfigurationSeeder extends Seeder
{
    /**
     * Seed the application's configuration settings
     */
    public function run(): void
    {
        $settings = [
            // System Configuration
            [
                'key' => 'app.name',
                'value' => 'Candidacy',
                'type' => 'string',
                'category' => 'system',
                'description' => 'Application name displayed in UI',
                'is_public' => true,
                'service_scope' => 'all',
                'requires_restart' => false,
            ],
            [
                'key' => 'app.company_name',
                'value' => 'Candidacy Inc.',
                'type' => 'string',
                'category' => 'system',
                'description' => 'Company name for branding',
                'is_public' => true,
                'service_scope' => 'all',
                'requires_restart' => false,
            ],
            [
                'key' => 'app.contact_email',
                'value' => 'contact@candidacy.com',
                'type' => 'string',
                'category' => 'system',
                'description' => 'Contact email for support',
                'is_public' => true,
                'service_scope' => 'all',
                'requires_restart' => false,
            ],
            [
                'key' => 'app.candidate_portal_url',
                'value' => 'http://localhost:5173',
                'type' => 'string',
                'category' => 'system',
                'description' => 'Base URL for candidate self-service portal',
                'is_public' => false,
                'service_scope' => 'candidate-service',
                'requires_restart' => false,
            ],
            [
                'key' => 'app.timezone',
                'value' => 'UTC',
                'type' => 'string',
                'category' => 'system',
                'description' => 'Default timezone for the application',
                'is_public' => false,
                'service_scope' => 'all',
                'requires_restart' => false,
            ],
            [
                'key' => 'app.language',
                'value' => 'en',
                'type' => 'string',
                'category' => 'system',
                'description' => 'Default language',
                'is_public' => false,
                'service_scope' => 'all',
                'requires_restart' => false,
            ],

            // AI Configuration
            [
                'key' => 'ai.provider',
                'value' => 'ollama',
                'type' => 'string',
                'category' => 'ai',
                'description' => 'AI provider: ollama or openrouter',
                'is_public' => false,
                'service_scope' => 'ai-service,document-parser-service',
                'requires_restart' => false,
                'validation_rules' => ['in:ollama,openrouter'],
            ],
            [
                'key' => 'ai.generation.timeout',
                'value' => '300',
                'type' => 'integer',
                'category' => 'ai',
                'description' => 'AI generation timeout in seconds',
                'is_public' => false,
                'service_scope' => 'ai-service',
                'requires_restart' => false,
                'validation_rules' => ['integer', 'min:30', 'max:600'],
            ],
            [
                'key' => 'ai.generation.temperature',
                'value' => '0.7',
                'type' => 'string',
                'category' => 'ai',
                'description' => 'AI temperature (0.0-1.0, lower = more deterministic)',
                'is_public' => false,
                'service_scope' => 'ai-service',
                'requires_restart' => false,
            ],
            [
                'key' => 'ai.generation.context_length',
                'value' => '8192',
                'type' => 'integer',
                'category' => 'ai',
                'description' => 'Context window size for AI generation',
                'is_public' => false,
                'service_scope' => 'ai-service',
                'requires_restart' => false,
                'validation_rules' => ['integer', 'min:2048', 'max:32768'],
            ],

            // Document Parser Configuration
            [
                'key' => 'document_parser.use_granite_docling',
                'value' => 'true',
                'type' => 'boolean',
                'category' => 'ai',
                'description' => 'Enable IBM Granite Docling for advanced PDF parsing',
                'is_public' => false,
                'service_scope' => 'document-parser-service',
                'requires_restart' => false,
            ],
            [
                'key' => 'document_parser.granite_model',
                'value' => 'ibm/granite-docling:258m',
                'type' => 'string',
                'category' => 'ai',
                'description' => 'Granite Docling model name',
                'is_public' => false,
                'service_scope' => 'document-parser-service',
                'requires_restart' => false,
            ],
            [
                'key' => 'document_parser.timeout',
                'value' => '60',
                'type' => 'integer',
                'category' => 'document_parser',
                'description' => 'Document parsing timeout in seconds',
                'is_public' => false,
                'service_scope' => 'document-parser-service',
                'requires_restart' => false,
                'validation_rules' => ['integer', 'min:10', 'max:300'],
            ],
            [
                'key' => 'document_parser.supported_types',
                'value' => '{"pdf": true, "docx": true, "doc": true, "txt": true}',
                'type' => 'json',
                'category' => 'document_parser',
                'description' => 'Enable or disable support for specific file types',
                'is_public' => true,
                'service_scope' => 'document-parser-service',
                'requires_restart' => false,
            ],
            [
                'key' => 'document_parser.pipeline',
                'value' => '["granite-docling", "smalot-pdfparser"]',
                'type' => 'json',
                'category' => 'document_parser',
                'description' => 'Preferred order of PDF parsers',
                'is_public' => false,
                'service_scope' => 'document-parser-service',
                'requires_restart' => false,
            ],
            [
                'key' => 'document_parser.image_resolution',
                'value' => '150',
                'type' => 'integer',
                'category' => 'document_parser',
                'description' => 'PDF-to-image resolution in DPI',
                'is_public' => false,
                'service_scope' => 'document-parser-service',
                'requires_restart' => false,
                'validation_rules' => ['integer', 'min:72', 'max:300'],
            ],

            // Recruitment Configuration
            [
                'key' => 'recruitment.auto_matching',
                'value' => 'true',
                'type' => 'boolean',
                'category' => 'ai',
                'description' => 'Automatically match candidates to vacancies',
                'is_public' => false,
                'service_scope' => 'matching-service',
                'requires_restart' => false,
            ],
            [
                'key' => 'recruitment.offer_expiry_days',
                'value' => '7',
                'type' => 'integer',
                'category' => 'recruitment',
                'description' => 'Number of days before job offers expire',
                'is_public' => false,
                'service_scope' => 'offer-service',
                'requires_restart' => false,
                'validation_rules' => ['integer', 'min:1', 'max:90'],
            ],
            [
                'key' => 'recruitment.interview_reminder_hours',
                'value' => '24',
                'type' => 'integer',
                'category' => 'recruitment',
                'description' => 'Hours before interview to send reminder',
                'is_public' => false,
                'service_scope' => 'interview-service',
                'requires_restart' => false,
                'validation_rules' => ['integer', 'min:1', 'max:168'],
            ],

            // Matching Configuration
            [
                'key' => 'matching.min_score_threshold',
                'value' => '40',
                'type' => 'integer',
                'category' => 'ai',
                'description' => 'Minimum match score to save (matches below this are discarded)',
                'is_public' => false,
                'service_scope' => 'matching-service',
                'requires_restart' => false,
                'validation_rules' => ['integer', 'min:0', 'max:100'],
            ],
            [
                'key' => 'matching.max_retry_attempts',
                'value' => '3',
                'type' => 'integer',
                'category' => 'ai',
                'description' => 'Maximum retry attempts if AI fails to provide RECOMMENDATION',
                'is_public' => false,
                'service_scope' => 'matching-service',
                'requires_restart' => false,
                'validation_rules' => ['integer', 'min:1', 'max:10'],
            ],
            [
                'key' => 'matching.display_threshold',
                'value' => '60',
                'type' => 'integer',
                'category' => 'ai',
                'description' => 'Threshold for displaying matches in UI (configurable filter)',
                'is_public' => false,
                'service_scope' => 'matching-service',
                'requires_restart' => false,
                'validation_rules' => ['integer', 'min:0', 'max:100'],
            ],

            // Storage Configuration
            [
                'key' => 'storage.cv_storage_limit_mb',
                'value' => '10',
                'type' => 'integer',
                'category' => 'storage',
                'description' => 'Maximum CV file size in MB',
                'is_public' => false,
                'service_scope' => 'candidate-service',
                'requires_restart' => false,
                'validation_rules' => ['integer', 'min:1', 'max:50'],
            ],
            [
                'key' => 'storage.max_upload_size',
                'value' => '10',
                'type' => 'integer',
                'category' => 'storage',
                'description' => 'Maximum upload size in MB',
                'is_public' => false,
                'service_scope' => 'candidate-service,document-parser-service',
                'requires_restart' => false,
                'validation_rules' => ['integer', 'min:1', 'max:100'],
            ],

            // Feature Flags
            [
                'key' => 'features.enable_ai',
                'value' => 'true',
                'type' => 'boolean',
                'category' => 'ai',
                'description' => 'Enable AI-powered features',
                'is_public' => false,
                'service_scope' => 'all',
                'requires_restart' => false,
            ],
            [
                'key' => 'features.enable_notifications',
                'value' => 'true',
                'type' => 'boolean',
                'category' => 'features',
                'description' => 'Enable email notifications',
                'is_public' => false,
                'service_scope' => 'notification-service',
                'requires_restart' => false,
            ],
            [
                'key' => 'features.enable_auto_matching',
                'value' => 'true',
                'type' => 'boolean',
                'category' => 'ai',
                'description' => 'Enable automatic candidate matching',
                'is_public' => false,
                'service_scope' => 'matching-service',
                'requires_restart' => false,
            ],

            // UI Customization
            [
                'key' => 'ui.login_background_image',
                'value' => '',
                'type' => 'string',
                'category' => 'ui',
                'description' => 'URL for login page background image',
                'is_public' => true,
                'service_scope' => 'frontend',
                'requires_restart' => false,
                'validation_rules' => ['nullable', 'url'],
            ],
            [
                'key' => 'ui.max_content_width',
                'value' => '1400',
                'type' => 'integer',
                'category' => 'ui',
                'description' => 'Maximum content width in pixels (0 = full width)',
                'is_public' => true,
                'service_scope' => 'frontend',
                'requires_restart' => false,
                'validation_rules' => ['integer', 'min:0', 'max:2560'],
            ],
            [
                'key' => 'ui.sidebar_width',
                'value' => '260',
                'type' => 'integer',
                'category' => 'ui',
                'description' => 'Sidebar width in pixels',
                'is_public' => true,
                'service_scope' => 'frontend',
                'requires_restart' => false,
                'validation_rules' => ['integer', 'min:200', 'max:400'],
            ],
            [
                'key' => 'ui.primary_color',
                'value' => '#4F46E5',
                'type' => 'string',
                'category' => 'ui',
                'description' => 'Primary brand color (hex)',
                'is_public' => true,
                'service_scope' => 'frontend',
                'requires_restart' => false,
            ],
            [
                'key' => 'ui.items_per_page',
                'value' => '20',
                'type' => 'integer',
                'category' => 'ui',
                'description' => 'Default items per page in lists',
                'is_public' => true,
                'service_scope' => 'frontend',
                'requires_restart' => false,
                'validation_rules' => ['integer', 'min:10', 'max:100'],
            ],
            [
                'key' => 'ui.date_format',
                'value' => 'YYYY-MM-DD',
                'type' => 'string',
                'category' => 'ui',
                'description' => 'Date display format',
                'is_public' => true,
                'service_scope' => 'frontend',
                'requires_restart' => false,
            ],
            [
                'key' => 'ui.time_format',
                'value' => 'HH:mm',
                'type' => 'string',
                'category' => 'ui',
                'description' => 'Time display format (HH:mm or hh:mm A)',
                'is_public' => true,
                'service_scope' => 'frontend',
                'requires_restart' => false,
            ],
            [
                'key' => 'ui.enable_dark_mode',
                'value' => 'false',
                'type' => 'boolean',
                'category' => 'ui',
                'description' => 'Enable dark mode by default',
                'is_public' => true,
                'service_scope' => 'frontend',
                'requires_restart' => false,
            ],

            // Service URLs (Internal)
            [
                'key' => 'services.ai_service_url',
                'value' => 'http://ai-service:8080',
                'type' => 'string',
                'category' => 'services',
                'description' => 'Internal AI service URL',
                'is_public' => false,
                'service_scope' => 'candidate-service,vacancy-service,matching-service',
                'requires_restart' => false,
                'validation_rules' => ['url'],
            ],
            [
                'key' => 'services.document_parser_url',
                'value' => 'http://document-parser-service:8080',
                'type' => 'string',
                'category' => 'services',
                'description' => 'Internal document parser service URL',
                'is_public' => false,
                'service_scope' => 'candidate-service',
                'requires_restart' => false,
                'validation_rules' => ['url'],
            ],
            [
                'key' => 'services.notification_service_url',
                'value' => 'http://notification-service:8080',
                'type' => 'string',
                'category' => 'services',
                'description' => 'Internal notification service URL',
                'is_public' => false,
                'service_scope' => 'interview-service,offer-service,onboarding-service',
                'requires_restart' => false,
                'validation_rules' => ['url'],
            ],

            // Email Configuration
            [
                'key' => 'email.from_address',
                'value' => 'noreply@candidacy.local',
                'type' => 'string',
                'category' => 'email',
                'description' => 'Default sender email address',
                'is_public' => false,
                'service_scope' => 'notification-service',
                'requires_restart' => false,
                'validation_rules' => ['email'],
            ],
            [
                'key' => 'email.from_name',
                'value' => 'Candidacy',
                'type' => 'string',
                'category' => 'email',
                'description' => 'Default sender name',
                'is_public' => false,
                'service_scope' => 'notification-service',
                'requires_restart' => false,
            ],
            [
                'key' => 'email.reply_to_address',
                'value' => 'support@candidacy.local',
                'type' => 'string',
                'category' => 'email',
                'description' => 'Reply-to email address',
                'is_public' => false,
                'service_scope' => 'notification-service',
                'requires_restart' => false,
                'validation_rules' => ['email'],
            ],
            [
                'key' => 'email.signature',
                'value' => 'Best regards,\nThe Candidacy Team',
                'type' => 'string',
                'category' => 'email',
                'description' => 'Email signature text',
                'is_public' => false,
                'service_scope' => 'notification-service',
                'requires_restart' => false,
            ],
        ];

        foreach ($settings as $setting) {
            Setting::updateOrCreate(
                ['key' => $setting['key']],
                $setting
            );
        }

        $this->command->info('Configuration settings seeded successfully!');
        $this->command->info('Total settings: ' . count($settings));
    }
}
